apiVersion: v1
kind: Service
metadata:
    name: mysql-service
    labels:
        app: mysql
spec:
    selector:
        app: mysql
    type: ClusterIP
    ports:
        - port: 3306
          name: mysql
          targetPort: 3306

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mysql-pvc
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-deployment
    labels:
        app: mysql
spec:
    selector:
        matchLabels:
            app: mysql
    replicas: 1
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
                - name: mysql-container
                  image: image_mysql
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 3306
                        name: mysql
                  volumeMounts:
                      - name: mysql-pv
                        mountPath: /var/lib/mysql/
            volumes:
                - name: mysql-pv
                  persistentVolumeClaim:
                      claimName: mysql-pvc